name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test_gcc:
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:ubuntu-build-gcc

    steps:
    - uses: actions/checkout@v2

    - name: Build SSVM-napi using gcc
      run: |
        JOBS=max npm install --fallback-to-build --update-binary .

  build_test_clang:
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:ubuntu-build-clang

    steps:
    - uses: actions/checkout@v2

    - name: Build SSVM-napi using clang
      run: |
        JOBS=max npm install --fallback-to-build --update-binary .
