name: Main Workflow

on:
  push:
    branches:
      - master
      - '**/test*'
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        cc: ['clang', 'gcc']
        include:
          - cc: 'clang'
            cxx: 'clang++'
          - cc: 'gcc'
            cxx: 'g++'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get install llvm-dev liblld-10-dev libboost-all-dev

    - name: Build SSVM-napi with ${{ matrix.cc }}
      uses: './.github/actions/build-from-source'
      with:
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}

    - name: Test SSVM-napi built with ${{ matrix.cc }}
      run: |
        JOBS=max npm test
